name: pelato_markazi
description: A new project for pelato markazi salon
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.5
  get: ^4.6.6
  persian_number_utility: ^1.1.3
  connectivity_plus: ^4.0.2
  iconsax: ^0.0.8
  dio: ^5.3.2
  package_info_plus: ^4.1.0
  shared_preferences: ^2.2.1
  carousel_slider: ^4.2.1
  intl: ^0.18.1
  flutter_map: ^5.0.0
  latlong2: ^0.9.0
  toastification:
    git: https://github.com/payam-zahedi/toastification.git
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
   - assets/images/

  fonts:
    - family: Sans
      fonts:
        - asset: assets/fonts/IRANSANS.TTF
        - asset: assets/fonts/IRANSANS_BOLD.TTF
          weight: 700
        - asset: assets/fonts/IRANSANS_BLACK.TTF
          weight: 900

    - family: Kalameh
      fonts:
        - asset: assets/fonts/KALAMEH_REGULAR.TTF
        - asset: assets/fonts/KALAMEH_BOLD.TTF
          weight: 700
        - asset: assets/fonts/KALAMEH_BLACK.TTF
          weight: 900